services:
  dev-blog:
    build: .
    image: dev-vlahx-engine:latest
    container_name: dev-vlahx
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      APP_PORT: "8000"
      APP_RELOAD: "true"
    volumes:
      - ./app:/app/app
      - ./db:/app/db
      - ./main.py:/app/main.py
      - ./run.py:/app/run.py
    networks:
      - s366

networks:
  s366:
    external: true
