from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from app.core.config import APP_DIR, PROJECT_ROOT, get_active_theme


@dataclass(frozen=True)
class ThemeInfo:
    slug: str
    name: str
    author: str
    version: str | None = None
    supports_color_scheme_toggle: bool = False
    is_builtin: bool = False


def _safe_theme_slug(raw: str) -> str | None:
    s = (raw or "").strip().lower()
    if not s:
        return None
    ok = set("abcdefghijklmnopqrstuvwxyz0123456789_-")
    if any(ch not in ok for ch in s):
        return None
    return s


def list_installed_themes() -> list[ThemeInfo]:
    """
    Detectează teme instalate din `app/themes/<slug>/`.

    Asset-urile statice rămase fără template sau manifest nu reprezintă o temă
    instalată și nu trebuie afișate în administrare.
    """
    out: list[ThemeInfo] = [load_theme_info("minimal")]
    base = APP_DIR / "themes"
    slugs: set[str] = set()

    if base.is_dir():
        for p in base.iterdir():
            if not p.is_dir():
                continue
            slug = _safe_theme_slug(p.name)
            if slug and slug != "minimal" and ((p / "theme.json").is_file() or (p / "templates").is_dir()):
                slugs.add(slug)

    for slug in sorted(slugs):
        out.append(load_theme_info(slug))
    return out


def is_theme_installed(slug: str) -> bool:
    normalized = _safe_theme_slug(slug)
    if normalized == "minimal":
        return True
    return normalized is not None and any(
        theme.slug == normalized for theme in list_installed_themes()
    )


def load_theme_info(theme_slug: str) -> ThemeInfo:
    slug = _safe_theme_slug(theme_slug) or "minimal"
    if slug == "minimal":
        return ThemeInfo(
            slug="minimal",
            name="Minimal",
            author="VlahX Core",
            version="1.0.0",
            supports_color_scheme_toggle=True,
            is_builtin=True,
        )
    manifest = APP_DIR / "themes" / slug / "theme.json"
    if not manifest.is_file():
        if slug == "default":
            # Default theme is always present even without a manifest.
            return ThemeInfo(
                slug="default",
                name="Default",
                author="Core",
                supports_color_scheme_toggle=True,
            )
        return ThemeInfo(slug=slug, name=slug, author="Unknown")
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            raise ValueError("invalid manifest")
        name = str(data.get("name") or slug).strip() or slug
        author = str(data.get("author") or "Unknown").strip() or "Unknown"
        version = str(data.get("version")).strip() if data.get("version") else "1.0.0"
        supports = bool(
            data.get(
                "supports_color_scheme_toggle", True if slug == "default" else False
            )
        )
        return ThemeInfo(
            slug=slug,
            name=name,
            author=author,
            version=version,
            supports_color_scheme_toggle=supports,
        )
    except Exception:
        if slug == "default":
            return ThemeInfo(
                slug="default",
                name="Default",
                author="Core",
                version="1.0.0",
                supports_color_scheme_toggle=True,
            )
        return ThemeInfo(slug=slug, name=slug, author="Unknown", version="1.0.0")


def active_theme_info() -> ThemeInfo:
    return load_theme_info(get_active_theme())


def sync_active_theme_css() -> None:
    """Copiază CSS-ul temei active într-un asset static agregat."""
    active_slug = get_active_theme()
    source = APP_DIR / "themes" / active_slug / "theme.css"
    target = APP_DIR / "static" / "css" / "themes.css"
    target.parent.mkdir(parents=True, exist_ok=True)

    base_css_path = APP_DIR / "static" / "site.css"
    base_css = base_css_path.read_text(encoding="utf-8") if base_css_path.is_file() else ""
    theme_css = source.read_text(encoding="utf-8") if source.is_file() else ""
    content = (
        "/* Generated by VlahX Core. Do not edit manually. */\n"
        f"/* Active theme: {active_slug} */\n"
        + base_css
        + "\n\n/* Theme overrides */\n"
        + theme_css
    )
    target.write_text(content, encoding="utf-8")


def set_active_theme(slug: str) -> None:
    from app.core.site_settings import write_settings
    s = _safe_theme_slug(slug)
    if not s or not is_theme_installed(s):
        return
    write_settings({"ACTIVE_THEME": s})
    sync_active_theme_css()


